config/routes.rb
Rails.application.routes.draw do
  root 'cookies#index'
  resources :cookies

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def new
  end

  def index
  end

  def create
    cookies[params[:key].to_sym] = {
      value: params[:value],
      domain: params[:domain],
      secure: params[:secure],
    }
    redirect_to '/'
  end

  def destroy
    cookies.delete params[:id]
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cookies/index.html.erb
<p>Here's all the cookies I can see server-side:</p>
<ul>
  <% cookies.each do |cookie| %>
    <li>
      <strong><%= cookie[0] %>:</strong> <%= cookie[1] %> <%= link_to 'Delete', cooky_path(id: cookie[0]), method: :delete, data: { confirm: 'Are you sure' } %>
    </li>
  <% end %>
</ul>
<%= link_to 'Set a new cookie from the server.', new_cooky_path %>

app/views/cookies/new.html.erb
<p>Tell me what kind of cookie to set</p>
<%= form_tag cookies_path, method: :post do %>
  <%= label_tag(:key, 'Key') %>
  <%= text_field_tag(:key) %>
  <%= label_tag(:value, 'Value') %>
  <%= text_field_tag(:value) %>
  <%= label_tag(:domain, 'Domain') %>
  <%= text_field_tag(:Domain) %>
  <%= label_tag(:secure, 'Secure') %>
  <%= check_box_tag(:secure) %>
  <%= label_tag(:http_only, 'Http Only') %>
  <%= check_box_tag(:http_only) %>

  <%= submit_tag('Submit') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieJar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>